In [1]:
print("Hello World")

Hello World


In [2]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np
a1 = np.array([1,2,3])
a2 = np.array([[1,2],[3,4]])
a3 = np.array([[[1,2],[3,4]],
               [[5,6],[7,8]]])
print(a1)
print(a2)
print(a3)

[1 2 3]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [8]:
import numpy as np
a0 = np.zeros((3,3))
a1 = np.ones((2,2))
ar = np.arange(0,10,2)

print(a0)
print(a1)
print(ar)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[0 2 4 6 8]


In [11]:
import numpy as np
a1 = np.array([10,20,30,40,50])
print(a1[2])
print(a1[-1])

a2 = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(a2[1,0])

30
50
4


In [13]:
import numpy as np
a = np.array([[1,2,3],
              [4,5,6]])

print(a[1:2])
print(a[:,1])

[[4 5 6]]
[2 5]


In [1]:
import numpy as np

a = np.array([10,20,30,40,50,60])
idx = np.array([1,3,5])
print(a[idx])

cond = a > 30
print(a[cond])

[20 40 60]
[40 50 60]


In [2]:
import numpy as np

x = np.array([1,2,3])
y = np.array([4,5,6])

print(x + y)
print(x - y)
print(x * y)
print(x / y)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [3]:
import numpy as np
a = np.array([-3,-1,0,1,3])
print(np.absolute(a))

[3 1 0 1 3]


In [4]:
import numpy as np
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
res = np.add(a1,a2)
print(res)

[5 7 9]


In [5]:
import numpy as np
dtype = [('name','S10'),('year',int),('cgpa',float)]
vals = [('Hrithik',2009,8.5),
        ('Ajay',2008,8.7),
        ('Pankaj',2008,7.9),
        ('Aakash',2009,9.0)]

a = np.array(vals,dtype=dtype)
print(np.sort(a,order='name'))
print(np.sort(a,order=['year','cgpa']))
        

[(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
[(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]


In [6]:
import numpy as np
A = np.array([[1,2],
             [5,6]])
res = np.dot(A,A)
print(res)

[[11 14]
 [35 46]]
